### PR TITLE
Rethore merge from CFMTech org

### PR DESCRIPTION
**Pull request by lebigot**

### CODE REVIEW

**Comment by kifran** [comment]
Merci

**Comment by kifran** [comment]
@jdhalimi  can you add a comment to the PR?

**Comment by jdhalimi** [comment]
Are u you ou ok now ?

**Comment by lebigot** [comment]
Franck, are you getting notifications from other _participants_?

**Comment by lebigot** [comment]
Yes, we're OK. Can you merge?

**Comment by jdhalimi** [comment]
Done with no sqach

**Pull request merged**
